### ISSUE TITLE
Running command against changed file

### ISSUE THREAD

**Issue by nickhammond** [AlexB52/retest#76]
Hey @AlexB52! Really enjoying retest, really lightweight and simple. 

I wanted to ping you to see if you had anything in mind or if this is something you have a workflow for. I'd like to run the test like you normally would but then also run rubocop against the changed file as well as the test file.  

Something like this:

``` shell
retest 'bin/rails test <test> && bundle exec rubocop <test> <changed>'
```

I noticed you just gsub `<test>` from the command `system command.gsub('<test>', cached_test_file)` but I think by the time it gets to the runner retest has already detected which spec|test file to use. The rubocop command will take as many files as you throw at it so they can just be listed one after another too.

**Comment by AlexB52** [comment]
Hi @nickhammond 

Thanks for the feedback and glad you enjoy retest.

Having a `<changed>` reference for retest seems like an excellent idea. I'll think about how this could work out. Few things need to be considered like when `<test>` and `<changed>` are the same for example. 

I'll definitely consider this for the next release but I can't promise a time frame.

**Comment by AlexB52** [comment]
Hello @nickhammond 

I have release [v1.5.0](https://github.com/AlexB52/retest/releases/tag/v1.5.0) which allows you to do what you want.

Based on your example I would recommend using 
```
retest 'bin/rails test <test> && bundle exec rubocop <changed>'
```

instead of 
```
retest 'bin/rails test <test> && bundle exec rubocop <test> <changed>'
```

For example, if we have a `post.rb` and `post_test.rb` files. Here are the different scenarios

A change on `post.rb` results in:
* `<changed> => post.rb`
* `<test> => post_test.rb`

A change on `post_test.rb` results in:
* `<changed> => post_test.rb`
* `<test> => post_test.rb`

Let me know if this works as expected :) 
Cheers
